version: "3"

services:
  jvm_web_benchmark:
    image: openjdk:15
    ports:
      - 18080:8080
    tty: true
    volumes:
      - .:/srv
    working_dir: /srv
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://0.0.0.0:4317"
      OTEL_RESOURCE_ATTRIBUTES: service.name=jvm_web_benchmark
    command: java -javaagent:./jars/opentelemetry-javaagent.jar -jar ./build/libs/jvm_web_benchmark-0.0.1-SNAPSHOT.jar
